name = "flore"
main = "dist/index.js"
compatibility_date = "2024-12-20"
compatibility_flags = [ "nodejs_compat" ]
no_bundle = true
assets = { directory = "dist", binding = "STATIC_ASSETS", experimental_serve_directly = true }

[[d1_databases]]
binding = "DB"
database_name = "flore-prod"
database_id = "4a894d57-685a-45f0-909d-8f19c8fb8222"
migrations_dir = "drizzle/migrations"


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
