// Generated by Wrangler by running `wrangler types ./app/binding.d.ts`

interface Env {
	AUTH_SECRET: string;
	AUTH_URL: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	DB: D1Database;
	STATIC_ASSETS: Fetcher;
}
